# compilateur
CC = gcc

# option de compilation
OPT = -Wall -ansi -pedantic -Wextra -g -O2

# liste des fichiers objets
OBJ = compilsep.o

# règle de production finale
tp : $(OBJ)
	$(CC) $(OBJ) -o tp

# règle de production pour chaque fichier
compilsep.o : 
